package com.example.demo.test01;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import com.itextpdf.html2pdf.HtmlConverter;

public class App2 
{
	public static final String HTML = "<p>"
			+ "	<p class=\"MsoNormal\" align=\"right\" style=\"text-align:right;\">"
			+ "		000001<i>通知流水号</i><b></b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\" align=\"center\" style=\"text-align:center;\">"
			+ "		<b>Mount Shikhar Financial Limited</b><b></b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\" align=\"center\" style=\"text-align:center;\">"
			+ "		<b>Loan Sanction Letter</b><b></b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\" align=\"center\" style=\"text-align:center;\">"
			+ "		<b>&nbsp;</b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\" align=\"center\" style=\"text-align:center;\">"
			+ "		&nbsp;"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b>Our Application/Loan No. </b>– <i><span>订单</span>I</i><i>D</i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>&nbsp;Date </b>- 16-MAR-18<i>申请日期</i>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b>Name of the Applicant</b>&nbsp;– <i>用户姓名</i>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b>Address </b>- DELHI,South West Delhi Rz 17/A Gali no 13 sitapuri part 1 New Delhi 110049 <i><span>用户</span>A</i><i>&nbsp;</i><i>卡上的居住地址</i><i></i>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b>Phone No. </b>9891128914 <i>用户注册手机号</i>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b><u>Subject</u></b><b>: </b><b><u>Sanction Letter towards Loan Number </u></b><b><i><span>订单</span>I</i></b><b><i>D. </i></b><b></b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b>&nbsp;&nbsp;&nbsp;</b><b></b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b>Dear Sir/Madam, </b><b></b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		We thank you for choosing<b>&nbsp;Mount Shikhar Financial Services Limited</b>&nbsp;as your financier for short term personal loan. With reference to your above application, we are pleased to inform you that, we have sanctioned you a loan facility as mentioned below."
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		&nbsp;"
			+ "	</p>"
			+ "	<table class=\"MsoTableGrid\" border=\"1\" cellspacing=\"0\" style=\"border:none;\">"
			+ "		<tbody>"
			+ "			<tr>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<b><span style=\"font-family:Calibri;font-size:10.5pt;\">Loan ID</span></b><b><span style=\"font-family:Calibri;font-size:10.5pt;\"></span></b>"
			+ "					</p>"
			+ "				</td>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<span style=\"font-family:Calibri;font-size:10.5000pt;\">Gt20200721003235</span><i><span style=\"font-family:宋体;color:#0000FF;font-size:10.5pt;\">借款<span>I</span></span></i><i><span style=\"font-family:Calibri;color:#0000FF;font-size:10.5pt;\">D</span></i><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "			</tr>"
			+ "			<tr>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<b><span style=\"font-family:Calibri;font-size:10.5pt;\">ID Number</span></b><b><span style=\"font-family:Calibri;font-size:10.5pt;\"></span></b>"
			+ "					</p>"
			+ "				</td>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<span style=\"font-family:Calibri;font-size:10.5000pt;\">HILPS5392R</span><i><span style=\"font-family:Calibri;color:#FF0000;font-size:10.5pt;\">&nbsp;</span></i><i><span style=\"font-family:Calibri;color:#0000FF;font-size:10.5pt;\">P</span></i><i><span style=\"font-family:宋体;color:#0000FF;font-size:10.5pt;\">an<span>卡卡号</span></span></i><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "			</tr>"
			+ "			<tr>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<b><span style=\"font-family:Calibri;font-size:10.5pt;\">Register Mobile Number</span></b><b><span style=\"font-family:Calibri;font-size:10.5pt;\"></span></b>"
			+ "					</p>"
			+ "				</td>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<span style=\"font-family:Calibri;font-size:10.5000pt;\">9891128914</span><i><span style=\"font-family:宋体;color:#0000FF;font-size:10.5pt;\">注册手机号</span></i><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "			</tr>"
			+ "			<tr>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<b><span style=\"font-family:Calibri;font-size:10.5pt;\">Registered Email ID</span></b><b><span style=\"font-family:Calibri;font-size:10.5pt;\"></span></b>"
			+ "					</p>"
			+ "				</td>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<span style=\"font-family:Calibri;font-size:11.0000pt;\"><a href=\"mailto:aanusinha111@gmail.com\">aanusinha111@gmail.com</a></span>用户邮箱<span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "			</tr>"
			+ "			<tr>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<b><span style=\"font-family:Calibri;font-size:10.5pt;\">Sanction Date</span></b><b><span style=\"font-family:Calibri;font-size:10.5pt;\"></span></b>"
			+ "					</p>"
			+ "				</td>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<span style=\"font-family:Calibri;font-size:10.5000pt;\">22-Jul-20</span><i><span style=\"font-family:宋体;color:#0000FF;font-size:10.5pt;\">审核通过日期</span></i><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "			</tr>"
			+ "			<tr>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<b><span style=\"font-family:Calibri;font-size:10.5pt;\">Sanctioned Loan Amount</span></b><b><span style=\"font-family:Calibri;font-size:10.5pt;\"></span></b>"
			+ "					</p>"
			+ "				</td>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<span style=\"font-family:Calibri;font-size:10.5000pt;\">3000</span><i><span style=\"font-family:宋体;color:#0000FF;font-size:10.5pt;\">借款金额</span></i><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "			</tr>"
			+ "			<tr>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<b><span style=\"font-family:Calibri;font-size:10.5pt;\">Loan Tenure</span></b><b><span style=\"font-family:Calibri;font-size:10.5pt;\"></span></b>"
			+ "					</p>"
			+ "				</td>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<span style=\"font-family:Calibri;font-size:10.5000pt;\">14</span><i><span style=\"font-family:宋体;color:#0000FF;font-size:10.5pt;\">借款期限</span></i><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "			</tr>"
			+ "			<tr>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<b><span style=\"font-family:Calibri;font-size:10.5pt;\">Total Interest</span></b><b><span style=\"font-family:Calibri;font-size:10.5pt;\"></span></b>"
			+ "					</p>"
			+ "				</td>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<span style=\"font-family:Calibri;font-size:10.5000pt;\">39.90 </span><i><span style=\"font-family:宋体;color:#0000FF;font-size:10.5pt;\">利息</span></i><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "			</tr>"
			+ "			<tr>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<b><span style=\"font-family:Calibri;font-size:10.5pt;\">Platform Fee</span></b><span style=\"font-family:Calibri;font-size:10.5000pt;\">&nbsp;(incl. 18% GST)</span><span class=\"16\" style=\"font-family:Calibri;font-size:10.5000pt;\"></span><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<span style=\"font-family:Calibri;font-size:10.5000pt;\">531 </span><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "			</tr>"
			+ "			<tr>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<b><span style=\"font-family:Calibri;font-size:10.5pt;\">Valuation Fee </span></b><span style=\"font-family:Calibri;font-size:10.5000pt;\">(Incl. 18% GST)</span><span class=\"16\" style=\"font-family:Calibri;font-size:10.5000pt;\"></span><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<span style=\"font-family:Calibri;font-size:10.5000pt;\">177</span><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "			</tr>"
			+ "			<tr>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<b><span style=\"font-family:Calibri;font-size:10.5pt;\">Total Processing Fee </span></b><span style=\"font-family:Calibri;font-size:10.5000pt;\">(Platform + Valuation Fee</span><span class=\"16\" style=\"font-family:Calibri;font-size:10.5000pt;\"></span><span style=\"font-family:Calibri;font-size:10.5000pt;\">, including 18% GST)</span><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "				<td width=\"217\" valign=\"top\" style=\"border:1.0000pt solid windowtext;\">"
			+ "					<p class=\"MsoNormal\">"
			+ "						<span style=\"font-family:Calibri;font-size:10.5000pt;\">708 </span><i><span style=\"font-family:宋体;color:#0000FF;font-size:10.5pt;\">总服务费</span></i><span style=\"font-family:Calibri;font-size:10.5000pt;\"></span>"
			+ "					</p>"
			+ "				</td>"
			+ "			</tr>"
			+ "		</tbody>"
			+ "	</table>"
			+ "	<p class=\"MsoNormal\">"
			+ "		&nbsp;"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		&nbsp;"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		&nbsp;"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		&nbsp;"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		- All the applicable taxes, duties and levies would be additionally charged as per law."
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		- ROI will be as per applicable reference rate at the time of disbursal."
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		- This letter supersedes any sanction letter issued earlier, with reference to application number <i><span>订单</span>I</i><i>D </i>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		&nbsp;"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b>Special Conditions (as applicable) : </b><b></b>"
			+ "	</p>"
			+ "	<p class=\"19\" style=\"margin-left:18.0000pt;text-indent:-18.0000pt;\">"
			+ "		1.)&nbsp;Verification of the KYC documents/Application details submitted."
			+ "	</p>"
			+ "	<p class=\"19\" style=\"margin-left:18.0000pt;text-indent:-18.0000pt;\">"
			+ "		2.)&nbsp;Execution of Loan Agreement and other documents between you and, Mount Shikhar Financial Services LTD. as per its policy and format."
			+ "	</p>"
			+ "	<p class=\"19\" style=\"margin-left:18.0000pt;text-indent:-18.0000pt;\">"
			+ "		3.)&nbsp;Other terms and conditions mentioned overleaf."
			+ "	</p>"
			+ "	<p class=\"19\" style=\"margin-left:18.0000pt;text-indent:-18.0000pt;\">"
			+ "		4.)&nbsp;Final loan approval/disbursal is subject to application/details verification and successful bank transaction."
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		&nbsp;"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\" align=\"justify\" style=\"text-align:justify;\">"
			+ "		For any further query/complaint, please visit our website<b>&nbsp;</b><b><i>产品官网地址</i></b>&nbsp;or write us at <b><i>产品</i></b><b><i>客服</i></b><b><i>邮箱</i></b><i>&nbsp;</i>or&nbsp;call us at<b><i>产品</i></b><b><i>客服电话</i></b>. For any further escalation you may visit our website&nbsp;<b><i>NBFC</i></b><b><i>官网地址</i></b><b>.</b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		&nbsp;"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\" align=\"justify\" style=\"text-align:justify;\">"
			+ "		<b>Please sign this letter as token of your acceptance of the terms and conditions mentioned above and overleaf. </b><b>Further, your consent conveyed through electronic means will also amount to your acceptance to terms and conditions mentioned above.</b><b></b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\" align=\"justify\" style=\"text-align:justify;\">"
			+ "		<b>&nbsp;</b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b>&nbsp;</b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b>Accepted the offer</b><b></b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b>&nbsp;</b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		<b>&nbsp;Customer Signature</b>"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		&nbsp;<b>*Note</b>&nbsp;- This is electronically generated sanction letter and no sign is required from the issuer."
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
			+ "	</p>"
			+ "	<p class=\"MsoNormal\">"
			+ "		&nbsp;"
			+ "	</p>"
			+ "</p>"
			+ "<p>"
			+ "	<br />"
			+ "</p>";
	
	
    public static void main( String[] args ) throws FileNotFoundException, IOException  
    {
//    	HtmlConverter.convertToPdf(HTML, new FileOutputStream("string-to-pdf.pdf"));
//    	
//        System.out.println( "PDF Created!" );
        
//      	HtmlConverter.convertToPdf(new FileInputStream("index.html"),  new FileOutputStream("index-to-pdf.pdf"));
      	HtmlConverter.convertToPdf(new FileInputStream(HTML),  new FileOutputStream("index-to-pdf.pdf"));

            System.out.println( "PDF Created!" );
            
            
    }
}